# Generated by Django 5.2.7 on 2025-11-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_remove_course_average_rating_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.TextField(default='Аноним'),
            preserve_default=False,
        ),
    ]
