# Generated by Django 5.2.8 on 2025-11-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0004_author_course_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='platform',
        ),
    ]
