# Generated by Django 5.2.8 on 2025-12-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0005_remove_course_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='display_name',
            field=models.CharField(max_length=200),
        ),
    ]
